version: '3'
tasks:
    install:
        cmds:
            - go build -o bima
            - mv bima /usr/local/bin/bima
    commit:
        cmds:
            - git commit -am "{{.CLI_ARGS}}"
            - git push
    release:
        cmds:
            - git tag -a {{.CLI_ARGS}} -m "release {{.CLI_ARGS}}"
            - git push origin {{.CLI_ARGS}}
